name: FastAPI CI/CD

on:
  push:
    branches: ["develop"]
    paths:
      - "fastapi/**"
      - ".github/workflows/fastapi-deploy.yml"
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/handdoc-fastapi

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fastapi
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag (short sha)
        id: tags
        run: echo "sha_tag=${GITHUB_SHA::12}" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v6
        with:
          context: ./fastapi
          push: true
          tags: |
            docker.io/${{ env.IMAGE_NAME }}:latest
            docker.io/${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.sha_tag }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            export DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
            export TAG="latest"
            docker login -u "${DOCKER_USERNAME}" -p "${{ secrets.DOCKER_PASSWORD }}"
            docker pull docker.io/${DOCKER_USERNAME}/handdoc-fastapi:${TAG}
            docker network create handdoc-net || true
            docker compose -f /home/ec2-user/apps/handdoc/docker-compose.fastapi.yml up -d
            docker image prune -f
            docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}"
